[workspace]
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
channels = ["conda-forge"]
name = "imitation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
imitation = { path = ".", editable = true }
jax = { version = ">=0.4.34, <0.4.38", extras = ["cuda12"] }
mlflow = ">=3.4.0, <4"
ml-collections = ">=1.1.0, <2"
distrax = ">=0.1.5, <0.2"
tqdm = ">=4.67.1, <5"
ogbench = ">=1.1.5, <2"
flax = ">=0.10.4, <0.11"
gymnax = ">=0.0.9, <0.0.10"
navix = ">=0.7.4, <0.8"
warp-lang = ">=1.9.1, <2"
mujoco = "<3.3.7"
brax = ">=0.12.5, <0.13"
minari = { version = ">=0.5.3, <0.6", extras = ["all"] }
minigrid = ">=3.0.0, <4"
gymnasium = { version = ">=1.2.1, <2", extras = ["other", "atari", "accept-rom-licenses"] }
ale-py = ">0.11"
gymnasium-robotics = ">=1.4.1, <2"
